### ISSUE TITLE
Some example App, please

### ISSUE THREAD

**Issue by sigaev-pro** [jcass77/WTFIX#4]
Hello,

Do you have some example simple app, for example, that will only list securities available to trading to logger?

**Comment by jcass77** [comment]
The standard deployment will already log in and start logging messages that are sent and received (e.g. heartbeats).

You should also find multiple examples for constructing and sending messages, as well as applications for receiving and interpreting messages, in the default WTFIX pipeline as it is currently made available in the main branch of this project.

Anything more than that is really application-specific, and depends a lot on how the FIX server that you are connecting to has been configured - the market should have a specification available for you.

**Comment by jcass77** [comment]
Closing this for now - please submit a PR if you have any specific ideas on how the README / examples can be improved.
